version: "2.4"
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    network_mode: host
    pid: "host"
    volumes:
      - "~/docker_ws/ros2_ws:/ros2_ws"
      - /dev/:/dev/
      - type: bind
        source: "./entrypoint_ros.bash"
        target: "/entrypoint_ros.bash"
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=1
      - ROS_IP=192.168.0.20
      - ROS_MASTER_URI=http://127.0.0.1:11311
    restart: always
#    tty: true