version: "2.4"
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    network_mode: host
    pid: "host"
    volumes:
      - "~/docker_ws/ros2_ws:/ros2_ws"
      - /dev/:/dev/
      - type: bind
        source: "./entrypoint_ros.bash"
        target: "/entrypoint_ros.bash"
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=1
      - CYCLONEDDS_URI=/ros2_ws/cyclonedds.xml
    restart: always
#    tty: true